repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff
        args: [ --fix ]
        language_version: python3.12
        types_or: [ python, pyi ]
      - id: ruff-format
        language_version: python3.12
        types_or: [ python, pyi ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --no-strict-optional, --allow-untyped-defs, --disable-error-code=no-redef]
        language_version: python3.12
        files: ^merlin/
        additional_dependencies: [types-requests]
